### ISSUE TITLE
Query fee too high on mainnet

### ISSUE THREAD

**Issue by polybioz** [oraclize/ethereum-api#10]
I paid 0.02 ETH per query which is much higher than advertised $0.01/query in current ETH prices (~$40 => $0.8/query). See transaction logs of my contracts:
https://etherscan.io/address/0x443dcadf55a41d7caf347b4d925041065fec66f6#internaltx
https://etherscan.io/address/0x0b78438d1b83d529f192729734979c83f0369e56#internaltx

I also tried to call oraclize getPrice and it returns the same price I paid:
```
> var contractAddress = "0x001a589Dda0D6Be37632925EAf1256986b2c6AD0"
> var oraclize = web3.eth.contract(ABI).at(contractAddress)
> web3.fromWei(oraclize.getPrice.call("URL",1000000))
{ [String: '0.02033266799733865'] s: 1, e: -2, c: [ 2033266799733, 86500000000000 ] }
```

**Comment by bertani** [comment]
Hello @polybioz,

as explained in [our documentation](http://docs.oraclize.it/#pricing-ethereum), when calling `oraclize_query` you don't pay just for the price of the query (0.01 USD for the URL datasource w/o authenticity proofs), but you also cover the gas cost of the callback transaction that Oraclize will need to send back to your contract to deliver the result. The only exception is the first `oraclize_query` call from each contract, where you don't have to pay anything as we don't charge anything for the query and we do cover ourselves the cost we have for sending the callback transaction (up to 200k gas).

I won't dive into the first query case, as in your case you are specifying a custom gas cost of 1 million gas and so the first free query doesn't apply - but note that at current prices the 200k gas risk we take, is worth over 0.16 USD.

If we look at your specific case, for a callback gas cost of 1M, getPrice is returning an amount of 0.02033266799733865 ETH to be paid, around 0.82 USD. Your 1M gas is currently costing (with the default gasPrice of 20 GWei) more than 0.81 USD, so the actual fee you are paying for the query is less than 1 cent. The reason why it is not exactly 1 cent but lower, is that we update the onchain price from time to time and given the current volatility there could be some small difference.

By looking at your transactions, it seems like the callback transactions (for example [this one](https://etherscan.io/tx/0x82ef769d045e3347a6435db999dd967292e2ac75e76f062a9d6f9082983fe687)) never use more than ~180k gas. Setting the custom oraclize gas cost in your contract to 1M is probably way too high and hence costing much more, you could set it to something much lower than that.
This is due to the unused callback tx gas price not being refunded (as explained in our docs). There are two main reasons why we don't refund the unused gas cost of the callback gas:
* there is no way in principle to know in advance the exact gas cost of a tx _before_ it will be confirmed, you can just make an estimate but depending on the order of the txs in a block or even the block itself, the gas cost can vary a lot. Oraclize has to commit for the worst case, meaning that we have no choice but to ask you to pay for the full gas you want us to set in your callback tx
* after the tx is confirmed, there is no safe way in general to send back to the contract the unspent ETH as such contract should handle it (increasing its complexity) and will likely enter in an unknown state (or those funds would be lost there forever)
Given that, we have chosen to leave this choice up to the user when specifying the gas limit for the callback tx (which you do in `oraclize_query`, as a last optional argument - default is 200k gas). Any unused gas will not be refunded. The only expection is when you pay offchain for the Oraclize calls, the billing being different this whole problem doesn't apply.

As a consequence the title of this issue should be "Query fee too low on mainnet" instead :)


I hope this help!

**Comment by polybioz** [comment]
Thanks for the thorough explanation! It makes perfect sense now, I should pay more attention to my gas limit (and docs :)).

**Comment by casidiablo** [comment]
This makes it very tricky to choose a correct gas limit. As you already said, the number of gas units spent depends on many factors. So as a developer, the only _safe_ choice is to overestimate the gas limit, where you know you will lose some money (by giving it for free to oraclize) but at least the transaction will be completed.

> after the tx is confirmed, there is no safe way in general to send back to the contract the unspent ETH as such contract should handle it

Well, sure there are alternatives. Just, off the top of my head:

- Calls to oraclize could include a wallet address that unspent gas get matched to. And then, you can just provide a function that allows people to claim their unspent ether. I mean, if someone does use this in a production scale system we are easily talking about a few hundred bucks worth of unspent gas monthly, at least.

- You could make the `getPrice` function take into account how much gas has the contract given away to oraclize, and depending on that return a different price for the transaction.

Comparing it to the whole oraclize stack, the technology involved in making it work, and the geniuses behind it, one would think that implementing a fair alternative to "we will just take the unspent gas for ourselves" wouldn't be much of a problem.

**Comment by D-Nice** [comment]
We do already have a solution to this in testing. There's many issues trying to implement a fair on-chain solution that works autonomously, as the same solution cannot be applied to every contract. However, contracts even now have the ability to avoid unspent gas going to Oraclize, by allowing the caller to customize the callback gas manually (albeit the only benefit here is if the callback will exceed 200k gas, as 200k as the default minimum, and the other issue, if they're wrong, the callback will be broadcast, but won't be included as it will run out of gas). So that's a solution developers can do themselves.

The other solution we've been working on is an off-chain payment system, which we'll be looking to make available in the coming weeks, and are already testing it. You'll be able to pay us off-chain, so no charging happens on-chain, you will just be charged for the spent gas + oraclize fees of the queries.
