### ISSUE TITLE
Next deployment todos

### ISSUE THREAD

**Issue by D-Nice** [oraclize/ethereum-api#28]
- [x]  Make gasprice variable public in connector
 - [x]  Make getPrice constant in connector
 - [ ] Consider making reqc in connector public at next update, as well as gasprice and other variables. e.g. seeing gasprice would help eth-bridge figure out if it needs to send a tx to change gasprice.

**Comment by D-Nice** [comment]
@gskapka If these are met in the next connector, please checkmark them

**Comment by gskapka** [comment]
__Checkbox 1:__ Here, are we talking about the `addressCustomGasPrice` mapping? I'm guessing so since making the `uin256 gasPrice = 20e9` public when it's essentially constant is kinda pointless right?  So if it _is_ the mapping then no, it's not currently public.

__Checkbox 2:__ Done, now there's loads of overloads too for various usecases.

__Checkbox 3:__ The `requestCounter` mapping isn't public (yet) either.

***

So, assuming the above para's assumptions are correct, I've made the necessary changes that'll result in ticking all three check boxes in this issue, and __[PRd them here](https://github.com/oraclize/connector-update-priv/pull/127)__.

**Comment by gskapka** [comment]
### Update on this:L

__Checkbox 1__: `addressCustomGasPrice is now public & has tests covering that fact.

__Checkbox 2__: Actually not done, since the `oraclizeAPI` modifier needs to be on the `getPrice` fxns in case we switch connectors, and that modifier changes the state and so fxns using it can't be `view`. Instead, we discussed showing in the docs how a user might achieve the same thing in their own contract should they wish to. Not ideal but we don't really have a better solution due to the need for connector-change flexibility.

__Checkbox 3:__ The `requestCounter` is __not__ public and after vacilliating and making it so then reverting back again, it's been decided to keep it private so as not to foster any external dependencies on it.

**Comment by gskapka** [comment]
And so re this: suggest closing this issue and creating a new one to track the _new_ next-deployment-todos, ie, those we want in __v4__.

**Comment by D-Nice** [comment]
by v4, you mean v1.4? Sounds good, closing
