### ISSUE TITLE
Decrypted query error

### ISSUE THREAD

**Issue by rrubo** [oraclize/ethereum-api#78]
I have a random.org nested query, which was working a couple of weeks ago. Today, when I tried to query a random number, I got: 

```
ERROR HTTP query error
        [
    "datasources.decrypt.access_denied",
    "parsing_helper.wrong_path"
```

This is really frustrating, as I haven't changed anything in the code. 

When I removed the encrypted API key and inserted the decrypted one, the query worked just fine.

What could be the error?

**Comment by gskapka** [comment]
That parsing error is when there's an error traversing the response from the URL endpoint. A few reasons it could occur:

__1)__ If the format of the response is altered at the API level itself.

__2)__ If a malformed query results in trying to parse a `404` response or similar. 

__3)__ If an API key to a service has expired/been revoked resulting in a `403` (or similar).

Since you've ruled out `#3` & `#1` via your experiments so far, and we haven't changed anything on our side re the encryption, could you share your query code so we can investigate further? And also what network was this on?

**Comment by D-Nice** [comment]
To protect mainnet contracts from having their encrypted queries hijacked, there is a notion of ownership. The above error indicates that some mainnet contract is already using that encrypted query. If you updated to a new contract, you will have to regenerated the encrypted portion for each contract. 

If this in fact happened to an existing mainnet contract, let us know the address, and we'll take a look.

**Comment by ytrezq** [comment]
> I have a random.org nested query, which was working a couple of weeks ago. Today, when I tried to query a random number, I got:
> 
> ```
> ERROR HTTP query error
>         [
>     "datasources.decrypt.access_denied",
>     "parsing_helper.wrong_path"
> ```
> 
> This is really frustrating, as I haven't changed anything in the code.
> 
> When I removed the encrypted API key and inserted the decrypted one, the query worked just fine.
> 
> What could be the error?

@rrubo how did you get error details?

**Comment by gskapka** [comment]
@ytrezq - by using the `check query` tool along with the query's `chain id` here: https://app.provable.xyz/home/check_query
